name: PR Checklist

on: pull_request

env:
  CI: true

jobs:
  check:
    name: PR Checklist
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Lint Workspace & Code
        run: |
          yarn nx workspace-lint
          yarn affected:lint --all
      - name: Unit Tests
        run: yarn affected:test --all
      - name: Test Builds
        run: yarn affected:build --all
