name: Release

on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha
  pull_request:
    branches:
      - main
      - next
      - beta
      - alpha

env:
  CI: true

jobs:
  release:
    name: Build, Release & Publish
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Lint Workspace & Code
        run: yarn lint
      - name: Unit Tests
        run: yarn affected:test
      - name: Build, Release on GitHub & Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
